### ISSUE TITLE
Editor 406 error

### ISSUE THREAD

**Issue by sirkitree** [vrsites/vrsites.com#1]
>Whenever I try and save my edited room on VRSites.com I'm getting this error:
"An appropriate representation of the requested resource /edit_room2 could not be found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

>Is this a server side problem or something I'm doing wrong?

– origin: http://www.reddit.com/r/janusVR/comments/2sbl7n/vrsites_editor_406_error_message/

**Comment by sirkitree** [comment]
I'm definitely able to reproduce this by simply putting a blank line at the end of the file. That's the only way I've gotten it so far, so that is a great indicator of what to look for in the code.

**Comment by qster123** [comment]
The problem arose when I moved to GoDaddy and I'm sure it's something to do with the charset or the way the firebox code is being parsed - http://www.checkupdown.com/status/E406.html

This has been the first person with the error for many months so I didn't look into it further.
