### ISSUE TITLE
BUEditor Insert Location

### ISSUE THREAD

**Issue by davexoxide** [vrsites/vrsites.com#3]
Most editors are setup to insert markup when clicking the buttons directly where the cursor is at.
BUEditor is no different.

I wonder if it's possible to use regex to identify the closing of current element before inserting markup to avoid stuff like this.

```
<AssetScript src="<Ghost id="<Video id="<Object id="" collision_id="" locked="" pos="" xdir="" ydir="" zdir="" scale="" col="" />" pos="" fwd="" />" auto_play="true" />" />
```

**Comment by sirkitree** [comment]
BUEditor is on the new beta site, which isn't yet public. Mind moving this to https://github.com/vrsites/beta.vrsites.com/issues/ ?
