### ISSUE TITLE
beta.vrsites

### ISSUE THREAD

**Issue by asurazero** [vrsites/vrsites.com#6]
when clicking add asset script it adds AssetScript src='' where it should add AssetScript src=""
                                                                                       apostrophe(2x) not single quote.

**Comment by sirkitree** [comment]
Hi @asurazero! Thanks for reporting here :smile: 

This was brought up on the subreddit I think as well, to which I asked, "Why should it be a double quote? Is it breaking anything?"

It doesn't seem to break anything and I can't find a good reason to change it, but if there is one, I'm certainly open to discussing it.

**Comment by asurazero** [comment]
it broke my javascript for my blend shape

**Comment by asurazero** [comment]
true doesn't look like it broke anything.
