### ISSUE TITLE
beta.vrsites, avatar area

### ISSUE THREAD

**Issue by asurazero** [vrsites/vrsites.com#8]
Not really super important but would like to request a specific spot for our avatars data, my avatar personally is well over 2mb. - thanks for all the quick responses today.

**Comment by sirkitree** [comment]
Yup, we're discussing some options for this internally already too :smile: 

I think we'll most likely go with a new content type for everyone to upload files specific to avatars and then you can have multiple avatar nodes which we could list (like we do with rooms). Perhaps these could be shared and such then as well.

I'll update here once we get that in place.

dev note: tracking this internally here – https://github.com/vrsites/beta.vrsites.com/issues/76
